version: '3.8'

services:
  app:
    build: .
    env_file:
      - .env.prod
    volumes:
      - .:/app
    environment:
      - API_TOKEN=${API_TOKEN}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
